### ISSUE TITLE
VIF filtering

### ISSUE THREAD

**Issue by mikeDTI** [GenoML/genoml#10]
<em>Please make sure that this is a feature request.</em>

**System information**
- GenoML version (you are using): >1.04
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
VIF (variance inflation factor) prefiltering, set at NA, 5, 10 for predictors on the fly.

**Will this change the current api? How?**
Yes, faster prefiltering for python only build.

**Who will benefit with this feature?**
Everyone once Mike gets time to write it.

**Any Other info.**
;-/

**Comment by m-makarious** [comment]
This is in the Python version
