### ISSUE TITLE
Biowulf install optimization

### ISSUE THREAD

**Issue by mikeDTI** [GenoML/genoml#2]
<em>Please make sure that this is a feature request.</em>

**System information**
- GenoML version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

It runs on biowulf but commentary from Susan Chacko:

genoml is installed and the webpage ready (https://hpc.nih.gov/apps/genoml.html).  
My one concern is that the packages PRSice, GCTA, and Plink are installed for each user, which is redundant on a multi-user system where the applications and dependencies should be centrally installed. 
I put those binaries into the genoml conda bin directory, and modified check_dependencies.py to look there first, but it seems that the other python scripts also look in the users $HOME/.genoml area for these executables.

It would be really a good feature if the genoml install process put these executables into the genoml bin directory, if all the scripts looked in the genoml bin directory before $HOME/.genoml/, or if it searched the regular $PATH .
Lets look into this in the full python version

**Will this change the current api? How?**

only at install

**Who will benefit with this feature?**

biowulf users

**Any Other info.**

**Comment by xldrx** [comment]
I am suggesting to introduce an environment variable (e.g. `GENOML_DEP_DIR`).
If it is set, genome uses this directory to store and retrieve dependencies. The variable can be easily instantiated in `module`. Any objections?

**Comment by mikeDTI** [comment]
Agreed. Nice fix.

**Comment by xldrx** [comment]
Done. @ffaghri1 Please reflects this in the documentations.

**Comment by mikeDTI** [comment]
on pip now? thanks!

**Comment by xldrx** [comment]
yes
