### ISSUE TITLE
Option to skip tuning

### ISSUE THREAD

**Issue by xldrx** [GenoML/genoml#4]
The only complexity is whether an *untuned* trained model is able to do inference.
If it is, the implementation is straightforward. otherwise we may need to distinguish between inference-able models and non-inference-able models. @mikeDTI, @ffaghri1  thoughts?

**Comment by mikeDTI** [comment]
yes, because int he model file we create both ```model_tuned_bestModel.RData``` and ```model_bestModel.RData```. One is just the tuned version of the other.
This was actually an option buried somewhere in the initial bash runs we tested for GenoML ;-).

**Comment by xldrx** [comment]
Sounds good. I will try this and report back the results.

**Comment by mikeDTI** [comment]
cool.  good work.

**Comment by xldrx** [comment]
Done. @ffaghri1 Please reflects this in the documentations.

**Comment by xldrx** [comment]
Done. @ffaghri1 Please reflects this in the documentations.

**Comment by ffaghri1** [comment]
added a table with the optional flags. 
will need to add a page on recommendation, practices.

**Comment by mikeDTI** [comment]
Great work, will make general updates to website today as per our call last week.

Mike A. Nalls, PhD
Data science consultant
CEO, Data Tecnica International
mike@datatecnica.com
+1 (202) 468-1533

**Comment by ffaghri1** [comment]
I’ve added more t to the website. I’m adding best practices section today.
Maybe wait changing the docs after I added the new docs. Thanks

**Comment by mikeDTI** [comment]
Let me know when to start editing again, made some this morning (jet lag).

Mike A. Nalls, PhD
Data science consultant
CEO, Data Tecnica International
mike@datatecnica.com
+1 (202) 468-1533

**Comment by ffaghri1** [comment]
Ok, why don’t you make changes, then I’ll add move them to the new format
if necessary. Won’t be working on it till later today. Thanks

**Comment by mikeDTI** [comment]
👍
