### ISSUE TITLE
--version gives fail message, minor issue but annoying

### ISSUE THREAD

**Issue by mikeDTI** [GenoML/genoml#8]
<em>Please make sure that this is a bug.</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Mac 

- GenoML installed from (source or binary):

pip

- GenoML version:

1.0.3

- Python version:

3.7

**Describe the current behavior**

--version gives fail message, minor issue but annoying

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by xldrx** [comment]
Done
